appdict/urls.py
# pylint: disable=C0103
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
#from django.contrib import admin
from features.dicterm import views
from features.wikilenguaje.views import lenguaje_detallado
from django.conf import settings
from django.conf.urls.static import static
from appdict import views
from features.dicterm.admin import admin_site
urlpatterns = [
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^login/$', views.Autenticar_usuario.as_view(), name='login'),
    url(r'^admin/', admin_site.urls),
    url(r'^lenguajes/', include('features.wikilenguaje.urls', namespace='Lenguajes')),
    url(r'^lenguajes/(?P<nombre_lenguaje>[^\.]+)', lenguaje_detallado, name='lenguaje_detallado'),
    url(r'^terminos/', include('features.dicterm.urls', namespace='Terminos')),
    url(r'^$', views.index, name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

features/dicterm/urls.py
from django.conf.urls import url
from features.dicterm.views import index_terminos
urlpatterns = [
    url(r'^$', index_terminos, name= 'index_terminos'),
]

features/wikilenguaje/urls.py
from django.conf.urls import url, include
from features.wikilenguaje.views import index_lenguajes, lenguaje_view, lenguaje_detallado , buscarl

urlpatterns = [
    url(r'^$', index_lenguajes, name='index_lenguajes'),
    url(r'^nuevo$', lenguaje_view, name='lenguaje_crear'),
    url(r'^buscarl/?$', buscarl, name='buscar_lenguaje'),
    ##   url(r'^/(?P<id_lenguaje>\d+)/$', lenguaje_detallado, name='lenguaje_detallado'),
]

templates/login.html
{% extends "base/base.html" %}
{% load i18n %}
{% block content %}
{% if form.errors and not form.non_field_errors %}
{% block modal %}
<!-- Modal -->
<div class="modal fade" id="errModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 style="color: black" class="modal-title" id="exampleModalLabel">Error al inciar sesión</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
        <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
        <strong>Ho my God!</strong> {{ error }}
        </div>
        {% endfor %}
      </div>
      <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
{% endblock modal %}
<p class="errornote">
  {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the
  errors below." %}{% endif %}
</p>
{% endif %} 
{% if form.non_field_errors %} 
<script>
  $('#errModal').modal('show')
</script>
{% for error in form.non_field_errors %}
{% endfor %} 
{% endif %}
{% if user.is_authenticated %}
  <meta http-equiv="REFRESH" content="0;url=/">
{% else %}
<div class="row">
{% include "forms/frm_login.html" %}
</div>
</form>
{% endif %}
{% endblock %} 

templates/nav_bar.html
<nav class="navbar navbar-toggleable-sm navbar-light bg-faded nav nav-tabs-justified">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand colorblur" href="/">TradTerm APP</a>
  <div class="collapse navbar-collapse nav-tabs" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    {% with url_name=request.resolver_match.url_name %}
    {% if user.is_superuser %}
     <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle {% if url_name == 'index' %}active{% endif %} " data-toggle="dropdown" href="{% url 'index' %}" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
      <div class="dropdown-menu text-center">
        <p>User: {{ user.username }}</p>
        <p>Nombre: {{ user.first_name }} {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'admin:index' %}">Panel de control</a>
        <a class="dropdown-item" href="{% url 'admin:index' %}wikilenguaje/lenguaje/">Administrar Lenguajes</a>
        <a class="dropdown-item" href="{% url 'admin:index' %}dicterm/termino/">Administrar Terminos</a>
        <a class="dropdown-item" href="{% url 'admin:index' %}auth/user/">Administrar Staff</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'admin:index' %}auth/password_change/">Cambiar contraseña</a>
        <a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sesión</a>
      </div>
      {% endif %}
      
      </li>
      <li class="nav-item">
        <a class="nav-link {% if url_name == 'index_terminos' %}active{% endif %}" href="{% url 'Terminos:index_terminos' %}">Terminos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if url_name == 'index_lenguajes' %}active{% endif %}" href="{% url 'Lenguajes:index_lenguajes' %}">Lenguajes</a>
      </li>
 
    </ul>
  {% if url_name == 'index_lenguajes' or url_name == 'buscar_lenguaje' %}
  <form action="{% url 'Lenguajes:buscar_lenguaje' %}" class="form-inline" method="GET">
    <input name="query" class="form-control mr-sm-2" type="text" placeholder="Buscar">
    <button class="btn btn-outline-success sm-0" type="submit">Buscar</button>
  </form>
  {% endif %}
  {% endwith %}
  </div>
</nav>